on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      toxenvs:
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
      steps: ${{ steps.setup.outputs.steps }}
    steps:
    - id: setup
      run: |
        cat > set_outputs.py << EOF
        import argparse
        import os


        def main() -> int:
            for k, v in sorted(os.environ.items()):
                if 'INPUT' in k:
                    print(f'{k}: {v}')
            return 0


        if __name__ == '__main__':
            raise SystemExit(main())
        EOF
        python3 -m set_outputs

        # TODO: REMOVEME
        echo "::set-output name=matrix::{}"
        echo "::set-output name=steps::[]"
  main:
    needs: setup
    runs-on: ${{ inputs.os }}
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps: ${{ fromJSON(needs.setup.outputs.steps) }}
